version: "3.7"

volumes:
    node_modules_volume: {}

services:
    node:
        build: .
        container_name: node
        command: npm run dev
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - node_modules_volume:/app/node_modules/
